"""Alembic environment.

The URL is read from the same place the app reads it (`DUCKDOCS_DB_URL`) so a
migration can never run against a different database than the one serving
requests.
"""

from __future__ import annotations

import os
from logging.config import fileConfig

from alembic import context
from sqlalchemy import engine_from_config, pool

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

_url = config.get_main_option("sqlalchemy.url") or os.environ.get("DUCKDOCS_DB_URL", "")
if not _url:
    raise RuntimeError("Set DUCKDOCS_DB_URL (or sqlalchemy.url) before running migrations.")
config.set_main_option("sqlalchemy.url", _url)

# Revisions are written by hand rather than autogenerated: the ORM models live
# behind an optional import in app.repositories.sql, and a schema this small is
# clearer as explicit DDL than as a diff of a metadata object.
target_metadata = None


def run_migrations_offline() -> None:
    context.configure(url=_url, target_metadata=target_metadata, literal_binds=True)
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    with connectable.connect() as connection:
        context.configure(connection=connection, target_metadata=target_metadata)
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
